// ============================================================
// Student Helpdesk Agent — Page: About & Features
// ============================================================
// Landing page highlighting the MERN stack architecture,
// RAG capabilities, and academic/administrative features.
// ============================================================

import React from 'react';
import { Link } from 'react-router-dom';

export default function About() {
  return (
    <div className="main-content" style={{ overflowY: 'auto' }}>
      <div className="about-container">
        {/* Hero Section */}
        <section className="about-hero">
          <h1>🎓 Focused Student Helpdesk AI</h1>
          <p>
            An intelligent, production-grade AI companion built on the modern <strong>MERN Stack</strong>{' '}
            (MongoDB, Express.js, React.js, Node.js) with <strong>Retrieval-Augmented Generation (RAG)</strong>.{' '}
            Designed specifically to answer college students' academic and administrative queries instantly and accurately.
          </p>
          <Link to="/" className="cta-btn">
            <span>🚀</span> Start Asking Questions
          </Link>
        </section>

        {/* Feature Grid */}
        <section className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">📚</div>
            <h3>RAG Knowledge Base</h3>
            <p>
              Queries are matched against 15+ official college policy documents covering syllabus,
              fee structures, examination regulations, attendance rules, and hostel guidelines.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">🤖</div>
            <h3>Intelligent Offline Fallback</h3>
            <p>
              When OpenAI API connectivity is unavailable, the backend automatically switches to an
              intelligent vector/keyword matching database fallback without interrupting service.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">🧠</div>
            <h3>Personalized Context</h3>
            <p>
              Tailors administrative and academic guidance by automatically incorporating the student’s
              department, academic year, and previous conversation history into the prompt.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">⚡</div>
            <h3>Modern MERN Architecture</h3>
            <p>
              Built with Node.js and Express for high-performance REST APIs, MongoDB for persistent
              session document storage, and React.js with Vite for a responsive glassmorphism UI.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">🔍</div>
            <h3>Transparent Citations</h3>
            <p>
              Every response generated by the helpdesk agent cites the exact official college policy
              document or handbook section used, building trust and transparency.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">💡</div>
            <h3>Smart Follow-up Chips</h3>
            <p>
              Anticipates student needs by generating context-aware follow-up question chips after
              every turn, making complex procedures easy to navigate.
            </p>
          </div>
        </section>

        {/* Footer */}
        <footer style={{ textAlign: 'center', padding: '2rem 0', borderTop: '1px solid var(--border-subtle)', color: 'var(--text-muted)', fontSize: '0.9rem' }}>
          <p>Project: Student Helpdesk Agent • Serial No. 12 • Antigravity Iterative Method</p>
          <p style={{ marginTop: '0.4rem' }}>Built with Node.js, Express, MongoDB, Mongoose, React, Vite & OpenAI GPT-4o-Mini</p>
        </footer>
      </div>
    </div>
  );
}
